### PR TITLE
Task 5

### PR DESCRIPTION
**Pull request by alexandrmiee**
1 - File serverless.yml contains configuration for importProductsFile
    function
    3 - The importProductsFile lambda function returns a correct response
    which can be used to upload a file into the S3 bucket
    4 - Frontend application is integrated with importProductsFile lambda
    5 - The importFileParser lambda function is implemented and
    serverless.yml contains configuration for the lambda

    +1 - async/await is used in lambda functions
    +1 - At the end of the stream the lambda function should move the file
    from the uploaded folder into the parsed folder
    (move the file means that file should be copied into parsed folder,
    and then deleted from uploaded folder)

    FE: http://lukovnikovan-nodejs-aws-fe-cloudfront.s3-website-eu-west-1.amazonaws.com/admin/products

### CODE REVIEW

**Comment by NikaOrl** [comment]
Please, add a comment w/ links and description about what have been done and ping me. I'll take a look in the evening anyway.

For the moment: 
Score: 0/8

**Comment by skyRoma** [comment]
> Please, add a comment w/ links and description about what have been done and ping me. I'll take a look in the evening anyway.
> 
> For the moment:
> Score: 0/8

@NikaOrl Agree, but I think the score should be **3** (let's be more positive:) ):
**-1.** Frontend application is integrated with importProductsFile lambda (can't be checked)
**-1.** The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda (it's not implemented)
**-1**. The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket (Can't be checked)
**-1.** importProductsFile lambda is covered by unit tests (it's not covered)
**-1.** At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (it's not implemented)

**Comment by maksumov** [comment]
# Task Evaluation

## Main Tasks

- [x] - File serverless.yml contains configuration for importProductsFile function
- [ ] - The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket
- [ ] - Frontend application is integrated with importProductsFile lambda
- [ ] - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda

Score for main tasks: 1/5

## Additional (optional) tasks

- [x]  - async/await is used in lambda functions
- [ ]  - importProductsFile lambda is covered by unit tests (aws-sdk-mock can be used to mock S3 methods - https://www.npmjs.com/package/aws-sdk-mock)
- [ ]  - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into parsed folder, and then deleted from uploaded folder)

Score for additional tasks: 1/3

Total score: 2/8

**Review by maksumov — APPROVED** [review]

**Review by skyRoma — APPROVED** [review]

**Comment by NikaOrl** [comment]
@skyRoma I hoped that the PR will be changed during the day. For the moment agree w/ @maksumov and will change the score to 2/8

**Pull request merged**
